export const metadata = {
  title: 'MLSP 2024',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="es">
        <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        </head>
      <body>{children}</body>
    </html>
  )
}
